/**
 * (REMOTE-CODE-PAIRING) SRP-6a arithmetic, checked against something outside
 * this repository.
 *
 * The load-bearing test here is the RFC 5054 Appendix B anchor: published `k`,
 * `x`, `v`, `B`, `u` and `S` for the 1024-bit group and SHA-1, reproduced
 * unmodified by the same code the production 3072/SHA-256 profile runs. Vectors
 * generated by the implementation they are meant to check prove nothing; these
 * were written down by somebody else first.
 *
 * The production group gets a different kind of check — a primality proof — for
 * the same reason: there is no published `S` for it, but a mis-transcribed
 * modulus is not a safe prime, and Miller-Rabin says so.
 */

import { describe, expect, it } from "bun:test";
import { fileURLToPath } from "node:url";
import {
	SRP_1024_SHA1,
	SRP_3072_SHA256,
	type SrpOperationCounts,
	srpAssertClientPublic,
	srpBigIntToBytes,
	srpBytesToBigInt,
	srpComputeK,
	srpComputeU,
	srpComputeVerifier,
	srpComputeX,
	srpModPow,
	srpPad,
	srpSecretModPow,
	srpServerHandshake,
	srpSetOperationCounts,
} from "./srp";

function fromHex(value: string): Uint8Array {
	return new Uint8Array(Buffer.from(value.replace(/\s+/g, ""), "hex"));
}

function hex(bytes: Uint8Array): string {
	return Buffer.from(bytes).toString("hex");
}

function bigFromHex(value: string): bigint {
	return BigInt(`0x${value.replace(/\s+/g, "")}`);
}

// ---------------------------------------------------------------------------
// RFC 5054 Appendix B — the anchor
// ---------------------------------------------------------------------------

const RFC_SALT = fromHex("BEB25379 D1A8581E B5A72767 3A2441EE");
const RFC_K = bigFromHex("7556AA045AEF2CDD07ABAF0F665C3E818913186F");
const RFC_X = bigFromHex("94B7555AABE9127CC58CCF4993DB6CF84D16C124");
const RFC_V = bigFromHex(
	"7E273DE8696FFC4F4E337D05B4B375BEB0DDE1569E8FA00A9886D8129BADA1F1" +
		"822223CA1A605B530E379BA4729FDC59F105B4787E5186F5C671085A1447B52A" +
		"48CF1970B4FB6F8400BBF4CEBFBB168152E08AB5EA53D15C1AFF87B2B9DA6E04" +
		"E058AD51CC72BFC9033B564E26480D78E955A5E29E7AB245DB2BE315E2099AFB",
);
const RFC_A_PRIV = bigFromHex(
	"60975527035CF2AD1989806F0407210BC81EDC04E2762A56AFD529DDDA2D4393",
);
const RFC_B_PRIV = fromHex(
	"E487CB59D31AC550471E81F00F6928E01DDA08E974A004F49E61F5D105284D20",
);
const RFC_A_PUB = bigFromHex(
	"61D5E490F6F1B79547B0704C436F523DD0E560F0C64115BB72557EC44352E890" +
		"3211C04692272D8B2D1A5358A2CF1B6E0BFCF99F921530EC8E39356179EAE45E" +
		"42BA92AEACED825171E1E8B9AF6D9C03E1327F44BE087EF06530E69F66615261" +
		"EEF54073CA11CF5858F0EDFDFE15EFEAB349EF5D76988A3672FAC47B0769447B",
);
const RFC_B_PUB = bigFromHex(
	"BD0C61512C692C0CB6D041FA01BB152D4916A1E77AF46AE105393011BAF38964" +
		"DC46A0670DD125B95A981652236F99D9B681CBF87837EC996C6DA04453728610" +
		"D0C6DDB58B318885D7D82C7F8DEB75CE7BD4FBAA37089E6F9C6059F388838E7A" +
		"00030B331EB76840910440B1B27AAEAEEB4012B7D7665238A8E3FB004B117B58",
);
const RFC_U = bigFromHex("CE38B9593487DA98554ED47D70A7AE5F462EF019");
const RFC_S = bigFromHex(
	"B0DC82BABCF30674AE450C0287745E7990A3381F63B387AAF271A10D233861E3" +
		"59B48220F7C4693C9AE12B0A6F67809F0876E2D013800D6C41BB59B6D5979B5C" +
		"00A172B4A2A5903A0BDCAF8A709585EB2AFAFA8F3499B200210DCC1F10EB3394" +
		"3CD67FC88A2F39A4BE5BEC4EC0A3212DC346D7E474B29EDE8A469FFECA686E5A",
);

describe("(REMOTE-CODE-PAIRING) RFC 5054 Appendix B", () => {
	const group = SRP_1024_SHA1;

	it("reproduces k, x and v", () => {
		expect(srpComputeK(group)).toBe(RFC_K);
		const x = srpComputeX(group, RFC_SALT, "alice", "password123");
		expect(srpBytesToBigInt(x)).toBe(RFC_X);
		expect(srpComputeVerifier(group, x)).toBe(RFC_V);
	});

	it("reproduces A from the published a", () => {
		expect(srpModPow(group.g, RFC_A_PRIV, group.N)).toBe(RFC_A_PUB);
	});

	it("reproduces B, u and S from the published b", () => {
		const handshake = srpServerHandshake({
			group,
			verifier: RFC_V,
			clientPublic: srpPad(group, RFC_A_PUB),
			privateExponent: RFC_B_PRIV,
		});
		expect(srpBytesToBigInt(handshake.serverPublic)).toBe(RFC_B_PUB);
		expect(srpComputeU(group, RFC_A_PUB, RFC_B_PUB)).toBe(RFC_U);
		expect(srpBytesToBigInt(handshake.sharedSecret)).toBe(RFC_S);
	});

	it("the client half agrees with the server half", () => {
		// The reference client, written here rather than in `srp.ts`: the desktop
		// is only ever the server, and this doubles as an independent
		// implementation of the other side of the same arithmetic.
		const k = srpComputeK(group);
		const u = srpComputeU(group, RFC_A_PUB, RFC_B_PUB);
		const base =
			(((RFC_B_PUB - ((k * srpModPow(group.g, RFC_X, group.N)) % group.N)) %
				group.N) +
				group.N) %
			group.N;
		const clientS = srpModPow(base, RFC_A_PRIV + u * RFC_X, group.N);
		expect(clientS).toBe(RFC_S);
	});
});

// ---------------------------------------------------------------------------
// the production modulus is what it claims to be
// ---------------------------------------------------------------------------

/** Miller-Rabin. Deterministic enough for "did somebody fat-finger the hex". */
function isProbablePrime(n: bigint, rounds: number): boolean {
	if (n < 2n) return false;
	for (const small of [2n, 3n, 5n, 7n, 11n, 13n, 17n, 19n, 23n, 29n, 31n]) {
		if (n === small) return true;
		if (n % small === 0n) return false;
	}
	let d = n - 1n;
	let r = 0n;
	while (d % 2n === 0n) {
		d /= 2n;
		r += 1n;
	}
	const bases = [2n, 3n, 5n, 7n, 11n, 13n, 17n, 19n, 23n, 29n, 31n, 37n];
	for (let i = 0; i < rounds && i < bases.length; i += 1) {
		const a = bases[i] as bigint;
		let y = srpModPow(a, d, n);
		if (y === 1n || y === n - 1n) continue;
		let composite = true;
		for (let j = 1n; j < r; j += 1n) {
			y = (y * y) % n;
			if (y === n - 1n) {
				composite = false;
				break;
			}
		}
		if (composite) return false;
	}
	return true;
}

describe("(REMOTE-CODE-PAIRING) the production group", () => {
	it("is 3072 bits with g = 5", () => {
		expect(SRP_3072_SHA256.widthBytes).toBe(384);
		expect(SRP_3072_SHA256.g).toBe(5n);
		expect(SRP_3072_SHA256.N.toString(2).length).toBe(3072);
		expect(SRP_3072_SHA256.hashAlgorithm).toBe("sha256");
	});

	it("has a modulus that is a safe prime", () => {
		// No published S exists for this group, so the check that the hex above was
		// transcribed correctly is mathematical: a corrupted modulus is composite
		// with overwhelming probability, and it is certainly not a SAFE prime.
		expect(isProbablePrime(SRP_3072_SHA256.N, 6)).toBe(true);
		expect(isProbablePrime((SRP_3072_SHA256.N - 1n) / 2n, 6)).toBe(true);
	}, 120_000);
});

// ---------------------------------------------------------------------------
// padding and boundary rejection
// ---------------------------------------------------------------------------

describe("(REMOTE-CODE-PAIRING) PAD is fixed width, never minimal", () => {
	it("keeps leading zeros and refuses an overlong value", () => {
		expect(hex(srpBigIntToBytes(1n, 4))).toBe("00000001");
		expect(srpPad(SRP_3072_SHA256, 1n).length).toBe(384);
		expect(srpPad(SRP_3072_SHA256, SRP_3072_SHA256.N - 1n).length).toBe(384);
		expect(() => srpBigIntToBytes(0x10000n, 2)).toThrow("more than 2 bytes");
		expect(() => srpBigIntToBytes(-1n, 4)).toThrow("negative");
	});

	it("round-trips through bytes", () => {
		const value = SRP_3072_SHA256.N - 12345n;
		expect(srpBytesToBigInt(srpPad(SRP_3072_SHA256, value))).toBe(value);
		expect(srpBytesToBigInt(new Uint8Array(0))).toBe(0n);
	});
});

describe("(REMOTE-CODE-PAIRING) canonical and degenerate A are refused", () => {
	const group = SRP_3072_SHA256;
	const verifier = srpComputeVerifier(
		group,
		srpComputeX(group, new Uint8Array(16), "sc/v3 remote-pair", "12345678"),
	);
	const b = new Uint8Array(32).fill(7);
	function handshakeWith(A: bigint): void {
		srpServerHandshake({
			group,
			verifier,
			clientPublic: srpPad(group, A),
			privateExponent: b,
		});
	}

	it("rejects 0, 1, N-1 and anything at or above N", () => {
		// One rule covers every out-of-group value, including the `A mod N == 0`
		// cases (0, N, 2N): they are refused for being outside (0, N), never
		// reduced into it.
		expect(() => srpAssertClientPublic(group, 0n)).toThrow("outside (0, N)");
		expect(() => srpAssertClientPublic(group, 1n)).toThrow("degenerate");
		expect(() => srpAssertClientPublic(group, group.N - 1n)).toThrow(
			"degenerate",
		);
		expect(() => srpAssertClientPublic(group, group.N)).toThrow(
			"outside (0, N)",
		);
		expect(() => srpAssertClientPublic(group, group.N + 1n)).toThrow(
			"outside (0, N)",
		);
		expect(() => srpAssertClientPublic(group, group.N * 2n)).toThrow(
			"outside (0, N)",
		);
	});

	it("rejects them through the handshake too", () => {
		expect(() => handshakeWith(0n)).toThrow("outside (0, N)");
		expect(() => handshakeWith(1n)).toThrow("degenerate");
		expect(() => handshakeWith(group.N - 1n)).toThrow("degenerate");
	});

	it("rejects an A that is not exactly the modulus width", () => {
		expect(() =>
			srpServerHandshake({
				group,
				verifier,
				clientPublic: new Uint8Array(383).fill(9),
				privateExponent: b,
			}),
		).toThrow("exactly 384 bytes");
		expect(() =>
			srpServerHandshake({
				group,
				verifier,
				clientPublic: new Uint8Array(385).fill(9),
				privateExponent: b,
			}),
		).toThrow("exactly 384 bytes");
	});

	it("rejects a zero server private exponent", () => {
		expect(() =>
			srpServerHandshake({
				group,
				verifier,
				clientPublic: srpPad(group, 42n),
				privateExponent: new Uint8Array(32),
			}),
		).toThrow("private exponent is zero");
	});
});

// ---------------------------------------------------------------------------
// the fixed-window secret ladder agrees with the naive one, and costs the same
// ---------------------------------------------------------------------------

/**
 * Secret exponents (`x` and `b`) run on `srpSecretModPow`, a fixed 4-bit-window
 * ladder whose operation count does not depend on the exponent's bits. Two
 * separate properties are checked, and they are not the same property:
 *
 *  1. IT COMPUTES THE RIGHT NUMBER — against the independent square-and-multiply
 *     in the same module, on both groups, and (via `srpComputeVerifier`) against
 *     RFC 5054's published `v`. A ladder that is uniform but wrong would pair
 *     nothing.
 *  2. IT COSTS THE SAME — an injectable counter proves that exponents of wildly
 *     different Hamming weight perform IDENTICAL squarings and multiplies. This
 *     is the property the naive routine does not have and the reason this one
 *     exists; it is checked by counting operations, never by a wall clock.
 */
describe("(REMOTE-CODE-PAIRING) the fixed-window secret ladder", () => {
	for (const group of [SRP_1024_SHA1, SRP_3072_SHA256]) {
		it(`agrees with square-and-multiply on g^x for ${group.name}`, () => {
			for (const seed of ["12345678", "00000000", "99999999"]) {
				const x = srpComputeX(
					group,
					fromHex("000102030405060708090a0b0c0d0e0f"),
					"sc/v3 remote-pair",
					seed,
				);
				expect(srpComputeVerifier(group, x)).toBe(
					srpModPow(group.g, srpBytesToBigInt(x), group.N),
				);
			}
		});

		it(`agrees with square-and-multiply on awkward exponents for ${group.name}`, () => {
			const base = srpModPow(group.g, 0x1234567n, group.N);
			const exponents: readonly Uint8Array[] = [
				// every nibble zero — the case `table[0]` exists for
				new Uint8Array(32),
				// a single set bit, top and bottom
				fromHex(`80${"00".repeat(31)}`),
				fromHex(`${"00".repeat(31)}01`),
				// leading zero BYTES: the same number, zero-extended on the left
				fromHex(`${"00".repeat(16)}${"a5".repeat(16)}`),
				// every nibble set
				new Uint8Array(32).fill(0xff),
				// alternating nibbles, and a fixed pseudo-random value
				new Uint8Array(32).fill(0x0f),
				fromHex(
					"9f1c4a70b83e2d5619c7f0a4b28d3e615a0c9d7f42b8e1360af59c2d78e4b103",
				),
			];
			for (const exponent of exponents) {
				expect(srpSecretModPow(group, base, exponent)).toBe(
					srpModPow(base, srpBytesToBigInt(exponent), group.N),
				);
			}
		});

		it(`treats a short exponent as the same number for ${group.name}`, () => {
			const base = srpModPow(group.g, 0x99n, group.N);
			const short = fromHex("0badc0de");
			expect(srpSecretModPow(group, base, short)).toBe(
				srpSecretModPow(group, base, fromHex(`${"00".repeat(28)}0badc0de`)),
			);
		});
	}

	it("refuses an exponent wider than 32 bytes rather than truncating it", () => {
		expect(() =>
			srpSecretModPow(SRP_3072_SHA256, 7n, new Uint8Array(33).fill(1)),
		).toThrow("at most 32 bytes");
	});

	it("performs identical operations for low and high Hamming weight", () => {
		const group = SRP_3072_SHA256;
		const base = srpModPow(group.g, 0x2ff41n, group.N);
		const measure = (exponent: Uint8Array): SrpOperationCounts => {
			const counts: SrpOperationCounts = { squarings: 0, multiplies: 0 };
			srpSetOperationCounts(counts);
			try {
				srpSecretModPow(group, base, exponent);
			} finally {
				srpSetOperationCounts(null);
			}
			return counts;
		};

		// 64 windows x (4 squarings + 1 multiply), whatever the exponent is.
		const expected: SrpOperationCounts = { squarings: 256, multiplies: 64 };
		expect(measure(new Uint8Array(32))).toEqual(expected);
		expect(measure(new Uint8Array(32).fill(0xff))).toEqual(expected);
		expect(measure(fromHex(`${"00".repeat(31)}01`))).toEqual(expected);
		expect(
			measure(
				fromHex(
					"9f1c4a70b83e2d5619c7f0a4b28d3e615a0c9d7f42b8e1360af59c2d78e4b103",
				),
			),
		).toEqual(expected);
	});

	it("multiplies by a FULL-WIDTH one for a zero nibble", () => {
		// `table[0]` is `N + 1`: congruent to 1, so the result is unchanged, but a
		// full-width operand rather than a conspicuously cheap `1n`. Both halves
		// are asserted — the width, and the fact that it leaves the value alone.
		const group = SRP_3072_SHA256;
		const one = group.N + 1n;
		expect(one % group.N).toBe(1n);
		expect(one.toString(16).length).toBeGreaterThanOrEqual(
			group.widthBytes * 2,
		);
		// An all-zero exponent runs 64 zero-nibble multiplies and must still be 1.
		expect(srpSecretModPow(group, 12345n, new Uint8Array(32))).toBe(1n);
	});

	it("has no `createDiffieHellman` left in the module", async () => {
		// The native engine was measured at ~2.4 s per exponent on the Electron
		// runtime this app ships and was removed; a reintroduction is a
		// main-thread stall triggerable from an unauthenticated public host.
		const source = await Bun.file(
			fileURLToPath(new URL("./srp.ts", import.meta.url)),
		).text();
		expect(source).not.toContain("createDiffieHellman(");
	});

	for (const group of [SRP_1024_SHA1, SRP_3072_SHA256]) {
		it(`agrees on the whole handshake for ${group.name}`, () => {
			const x = srpComputeX(
				group,
				fromHex("0f0e0d0c0b0a09080706050403020100"),
				"sc/v3 remote-pair",
				"24681357",
			);
			const verifier = srpComputeVerifier(group, x);
			// A leading zero byte in b, so the short-private-value path is
			// exercised too.
			const b = fromHex(
				"00b1c2d3e4f5061728394a5b6c7d8e9fa0b1c2d3e4f5061728394a5b6c7d8e9f",
			);
			const A = srpModPow(group.g, 0x2ff41n, group.N);
			const handshake = srpServerHandshake({
				group,
				verifier,
				clientPublic: srpPad(group, A),
				privateExponent: b,
			});

			const k = srpComputeK(group);
			const expectedB =
				(((k * verifier) % group.N) +
					srpModPow(group.g, srpBytesToBigInt(b), group.N)) %
				group.N;
			expect(srpBytesToBigInt(handshake.serverPublic)).toBe(expectedB);

			const u = srpComputeU(group, A, expectedB);
			const base = (A * srpModPow(verifier, u, group.N)) % group.N;
			expect(srpBytesToBigInt(handshake.sharedSecret)).toBe(
				srpModPow(base, srpBytesToBigInt(b), group.N),
			);
			expect(handshake.serverPublic.length).toBe(group.widthBytes);
			expect(handshake.sharedSecret.length).toBe(group.widthBytes);
		});
	}

	it("a fresh b gives a different B and a different S for the same A", () => {
		const group = SRP_3072_SHA256;
		const verifier = srpComputeVerifier(
			group,
			srpComputeX(
				group,
				new Uint8Array(16).fill(3),
				"sc/v3 remote-pair",
				"13571357",
			),
		);
		const clientPublic = srpPad(group, srpModPow(group.g, 0x9911n, group.N));
		const first = srpServerHandshake({
			group,
			verifier,
			clientPublic,
			privateExponent: new Uint8Array(32).fill(0x11),
		});
		const second = srpServerHandshake({
			group,
			verifier,
			clientPublic,
			privateExponent: new Uint8Array(32).fill(0x22),
		});
		expect(hex(first.serverPublic)).not.toBe(hex(second.serverPublic));
		expect(hex(first.sharedSecret)).not.toBe(hex(second.sharedSecret));
	});
});
